# Generated by Django 5.1.6 on 2025-03-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('Roll', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Father_name', models.CharField(max_length=30)),
                ('Address', models.TextField()),
            ],
        ),
    ]
